import { expect, test } from "@playwright/test";
import { setupRegistration } from "./registration-fixture";
for (const reject of [false, true]) test(`student name editing uses audited endpoint and preserves draft; reject=${reject}`, async ({ page }) => {
  const { writes } = await setupRegistration(page, { reject });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/students");
  await page.getByRole("row").filter({ hasText: "UI-ONE" }).click();
  await page.getByPlaceholder("選択中のLINEアカウントへ送信するメッセージ").fill("生徒画面の返信下書き");
  await page.getByRole("link", { name: "名前を直す", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "LINE登録・修正", exact: true });
  await expect(dialog.getByText("相手のLINE表示名：登録試験LINE")).toBeVisible();
  await dialog.getByLabel("勉たんに表示する名前").fill("本　試験一郎（新）");
  await dialog.getByLabel("変更した先生・スタッフ名").fill("確認職員");
  await dialog.getByRole("button", { name: "この名前で保存", exact: true }).click();
  await expect.poll(() => writes.length).toBe(1);
  expect(writes).toEqual([{ path: "/api/students/UI-ONE/line-name", body: { line_user_id: "ui-line", alias_name: "本　試験一郎（新）", performed_by: "確認職員" } }]);
  if (reject) await expect(dialog.getByRole("status")).toContainText("保存できませんでした");
  await dialog.getByRole("button", { name: "← 生徒一覧に戻る", exact: true }).click();
  await expect(page.getByPlaceholder("選択中のLINEアカウントへ送信するメッセージ")).toHaveValue("生徒画面の返信下書き");
  if (!reject) await expect(page.getByRole("row").filter({ hasText: "UI-ONE" })).toContainText("本　試験一郎（新）");
});
