import {NextRequest} from 'next/server';
import {staffContext,staffResponse,staffErrorResponse,staffJsonBody,assertStaffMutationOrigin} from '@/lib/staff-auth-http';
import {InterviewError} from '@/lib/interview-core.mjs';
import {applyGeneratedAvailability,availabilityOverview,previewGeneratedAvailability} from '@/lib/interview-generated-availability';
export const dynamic='force-dynamic';export const maxDuration=120;
function assertAvailabilityAccess(staff:{role:string}){if(!['admin','office','employee','teacher'].includes(staff.role))throw new InterviewError('予約可能枠を作成する権限がありません。',403);}
const identity=(staff:{staffCode:string;displayName:string})=>({staffCode:staff.staffCode,displayName:staff.displayName});
export async function GET(request:NextRequest){let context;try{context=await staffContext(request);assertAvailabilityAccess(context.staff);const month=request.nextUrl.searchParams.get('month')??'';if(request.nextUrl.searchParams.get('overview')==='1'){if(!['admin','office'].includes(context.staff.role))throw new InterviewError('全体状況を確認する権限がありません。',403);return staffResponse(await availabilityOverview(context.dataClient,month),context);}const raw=request.nextUrl.searchParams.get('campusChoices');if(raw&&raw.length>2048)throw new InterviewError('校舎の選択を確認してください。');let campusChoices:unknown;try{campusChoices=raw?JSON.parse(raw):undefined;}catch{throw new InterviewError('校舎の選択を確認してください。');}return staffResponse(await previewGeneratedAvailability(context.dataClient,month,identity(context.staff),campusChoices,request.nextUrl.searchParams.get('startTime')??undefined),context);}catch(error){return error instanceof InterviewError?staffResponse({error:error.message},context,error.status):staffErrorResponse(error,context);}}
export async function POST(request:NextRequest){let context;try{assertStaffMutationOrigin(request);context=await staffContext(request);assertAvailabilityAccess(context.staff);const body=await staffJsonBody(request);const result=await applyGeneratedAvailability(context.dataClient,{month:String(body.month??''),identity:identity(context.staff),previewHash:String(body.previewHash??''),operationKey:String(body.operationKey??''),actor:context.staff.staffId,campusChoices:body.campusChoices,startTime:body.startTime as string|undefined});return staffResponse({saved:result},context);}catch(error){return error instanceof InterviewError?staffResponse({error:error.message},context,error.status):staffErrorResponse(error,context);}}
