'use client';
import Link from 'next/link';
import InterviewInvitations from './invitations';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import StaffEntry from '../self-study-room/staff-entry';
import FlowDialog from '@/components/flow-dialog';
import {canAccessInterviews} from '@/lib/interview-access.mjs';
import {describe} from '@/app/interviews/workspace';
import styles from '@/app/interviews/interviews.module.css';
type Time={date:string;start:string;end:string;teacher:string};
type Staff={staffId:string;staffCode:string;displayName:string;role:string};
type Choice={slotId:string;data:Time;available:boolean};
type RequestRow={id:string;studentName:string;status:string;version:number;choices:Choice[];note:string};
type Booking={id:string;status:string;version:number;notion_synced_version:number;notion_page_id:string|null;sync_error:string|null;data:Time&{studentName:string;method:string}};
type Slot={id:string;notion_page_id:string;published:boolean;source_available?:boolean;data:Time};
type Offer=Time&{pageId:string};
type State={snapshot:string;requests:RequestRow[];bookings:Booking[];slots:Slot[];loginReady:boolean};
type Operation={operationKey:string;action:string;[key:string]:unknown};
export default function InterviewDesk({entryCode='',initialTab='requests'}:{entryCode?:string;initialTab?:'requests'|'invitations'}){
 const [staff,setStaff]=useState<Staff|null>(null),[state,setState]=useState<State|null>(null),[ready,setReady]=useState(false),[code,setCode]=useState(entryCode),[password,setPassword]=useState('');
 const [tab,setTab]=useState<'requests'|'bookings'|'slots'|'invitations'>(initialTab),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState<Operation|null>(null),[invitationBusy,setInvitationBusy]=useState(false);
 const [selections,setSelections]=useState<Record<string,string>>({}),[offers,setOffers]=useState<Offer[]|null>(null);
 const [confirm,setConfirm]=useState<{op:Operation;title:string;detail:string;reject?:boolean}|null>(null),[reason,setReason]=useState('');
 const lock=useRef(false);
 const api=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(path,{...init,cache:'no-store'});const b=await r.json();if(!r.ok){if(r.status===401){setStaff(null);setState(null);setOffers(null);setConfirm(null);setRetry(null);}throw Object.assign(Error(b.error??'接続できませんでした。'),{status:r.status});}return b;},[]);
 const load=useCallback(async()=>{setState(await api('/api/staff/interview-requests'));},[api]);
 async function work(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await task();}catch(e){setMessage((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 useEffect(()=>{let active=true;void(async()=>{try{const r=await fetch('/api/staff/session',{cache:'no-store'});const b=await r.json();if(!active)return;if(r.ok){if(!canAccessInterviews(b.staff)){setMessage('現在は工藤さん・金城さんの受付です。');return;}setStaff(b.staff);await load();}else if(r.status!==401)setMessage(b.error);}catch(e){if(active)setMessage((e as Error).message);}finally{if(active)setReady(true);}})();return()=>{active=false;};},[load]);
 useEffect(()=>{if(!staff||busy||retry||confirm)return;let active=true,inFlight=false;const read=async()=>{if(inFlight||document.visibilityState==='hidden')return;inFlight=true;try{const r=await fetch('/api/staff/interview-requests',{cache:'no-store'});const b=await r.json();if(!active)return;if(r.ok)setState(b);else if(r.status===401){setStaff(null);setState(null);}}catch{/* The explicit refresh displays errors. */}finally{inFlight=false;}};const timer=setInterval(()=>void read(),30000);window.addEventListener('focus',read);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',read);};},[staff,busy,retry,confirm]);
 useEffect(()=>{if(tab!=='slots'||!staff||offers!==null)return;let active=true;void(async()=>{try{const body=await api('/api/staff/interview-requests?offers=1');if(active)setOffers(body.offers??[]);}catch(error){if(active)setMessage((error as Error).message);}})();return()=>{active=false;};},[api,offers,staff,tab]);
 async function login(e:FormEvent){e.preventDefault();await work(async()=>{const secret=password;setPassword('');const b=await api('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staffCode:code,password:secret})});if(!canAccessInterviews(b.staff))throw Error('現在は工藤さん・金城さんの受付です。');setStaff(b.staff);await load();});}
 async function save(op:Operation){await work(async()=>{setRetry(op);let b;try{b=await api(op.action==='cancel'?'/api/staff/interviews':'/api/staff/interview-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(op)});}catch(e){if((e as {status?:number}).status&&((e as {status:number}).status<500)){setRetry(null);setConfirm(null);await load();}throw e;}setRetry(null);setConfirm(null);await load();if(['publish','unpublish'].includes(op.action))setOffers(null);setMessage(b.notification?.message??b.sync?.message??(op.action==='approve'?'承認しました。':op.action==='cancel'?'予約を取り消しました。':'保存しました。'));});}
 const frozen=busy||!!retry||invitationBusy;
 const notice=message||retry?<>{message&&<p role="status">{message}</p>}{retry&&<><p>保存結果を確認できていません。</p><button disabled={busy} onClick={()=>void save(retry)}>保存結果を再確認</button></>}</>:undefined;
 function propose(op:Omit<Operation,'operationKey'>,title:string,detail:string,reject=false){setMessage('');setReason('');setConfirm({op:{...op,operationKey:crypto.randomUUID()} as Operation,title,detail,reject});}
 const pending=state?.requests.filter(r=>r.status==='pending')??[];
 return <main className={styles.screen}><header className={styles.header}><div><h1>面談の予約</h1><p>オンライン・45分</p></div>{staff&&<small>{staff.displayName}</small>}</header>
 {message&&!confirm&&<p role="status" className={styles.notice}>{message}</p>}
 {!ready?<p>読み込んでいます…</p>:!staff?<form className={styles.panel} onSubmit={login}><StaffEntry code={code} onChange={setCode} disabled={busy}/>{code&&<><label>パスワード<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>ログイン</button></>}</form>:<>
 <nav className={styles.tabs} aria-label="面談の表示"><button disabled={frozen} aria-pressed={tab==='requests'} onClick={()=>setTab('requests')}>申請 {pending.length>0?`(${pending.length})`:''}</button><button disabled={frozen} aria-pressed={tab==='bookings'} onClick={()=>setTab('bookings')}>確定予定</button><button disabled={frozen} aria-pressed={tab==='slots'} onClick={()=>setTab('slots')}>受付日程</button>{staff.staffCode==='KUDO'&&<button disabled={frozen} aria-pressed={tab==='invitations'} onClick={()=>setTab('invitations')}>アンケートから選ぶ</button>}</nav>
 <div className={styles.actions}><button disabled={frozen} onClick={()=>void work(async()=>{await load();if(tab==='slots')setOffers(null);})}>更新</button></div>
 {retry&&!confirm&&<div className={styles.notice}>{notice}</div>}
 {!state?<p>申請を読み込んでいます。</p>:<>
 {tab==='invitations'&&staff.staffCode==='KUDO'&&<InterviewInvitations staff={staff} onBusyChange={setInvitationBusy} onRequests={()=>{setTab('requests');void work(load);}} onSlots={()=>setTab('slots')}/>}
 {tab==='invitations'&&staff.staffCode!=='KUDO'&&<p className={styles.notice}>現在の日程案内は工藤専用の検証中です。一般保護者への送信はまだ開始していません。</p>}
 {tab==='requests'&&<section aria-label="面談の申請">{pending.length===0&&<p className={styles.empty}>確認待ちの申請はありません。</p>}{pending.map(row=>{const selected=selections[row.id]??row.choices.find(c=>c.available)?.slotId??'';return <article key={row.id} className={styles.panel}><h2>{row.studentName}さん</h2><div className={styles.choices}>{row.choices.map((choice,i)=><label className={styles.choice} key={choice.slotId}><input type="radio" name={'choice-'+row.id} checked={selected===choice.slotId} disabled={frozen||!choice.available} onChange={()=>setSelections({...selections,[row.id]:choice.slotId})}/>第{i+1}希望　{describe(choice.data)}{!choice.available&&<small>現在は選べません</small>}</label>)}</div>{row.note&&<p>{row.note}</p>}<div className={styles.actions}><button className={styles.primary} disabled={frozen||!row.choices.some(c=>c.available&&c.slotId===selected)} onClick={()=>propose({action:'approve',id:row.id,version:row.version,slotId:selected},'日程を承認',`${row.studentName}さん ／ ${describe(row.choices.find(c=>c.slotId===selected)!.data)}`)}>選んだ日程で承認</button><button disabled={frozen} onClick={()=>propose({action:'reject',id:row.id,version:row.version},'日程の再選択を依頼',row.studentName+'さん',true)}>別の日程を相談</button></div></article>;})}
 {state.bookings.some(b=>b.status==='pending')&&<p><Link className={styles.button} href="/staff/interviews/manage">職員が入力した承認待ちの面談を確認</Link></p>}</section>}
 {tab==='bookings'&&<section aria-label="確定した面談">{state.bookings.filter(b=>b.status==='confirmed').sort((a,b)=>a.data.date.localeCompare(b.data.date)||a.data.start.localeCompare(b.data.start)).map(b=><article className={styles.panel} key={b.id}><h2>{b.data.studentName}さん</h2><p>{describe(b.data)}<br/>{b.data.teacher} ／ {b.data.method==='Zoom'?'オンライン':b.data.method}</p><small>{b.notion_synced_version===b.version?'Notion反映済み':'Notion反映を確認してください'}</small>{b.sync_error&&<p className={styles.notice}>{b.sync_error}</p>}<div className={styles.actions}><button className={styles.danger} disabled={frozen} onClick={()=>propose({action:'cancel',snapshot:state.snapshot,id:b.id,version:b.version},'予約の取消',`${b.data.studentName}さん ／ ${describe(b.data)}`,true)}>予約を取り消す</button>{b.notion_synced_version!==b.version&&<button disabled={frozen} onClick={()=>void work(async()=>{const r=await api('/api/staff/interviews/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:b.id})});await load();setMessage(r.message);})}>Notion反映を再確認</button>}</div></article>)}{!state.bookings.some(b=>b.status==='confirmed')&&<p className={styles.empty}>確定した面談はありません。</p>}</section>}
 {tab==='slots'&&<section aria-label="保護者向けの受付日程">{!state.loginReady&&<p className={styles.notice}>保護者のLINEログインは接続準備中です。</p>}<h2>保護者に表示中</h2><p>各生徒には、台帳の担任と同じ先生の枠だけを表示します。保護者はその中から第1〜第3希望を選びます。</p>{state.slots.filter(s=>s.published&&s.source_available!==false).map(s=><article key={s.id} className={styles.panel}><strong>{describe(s.data)}</strong><small>{s.data.teacher}先生</small><button disabled={frozen} onClick={()=>propose({action:'unpublish',pageId:s.notion_page_id},'日程の受付を停止',describe(s.data))}>保護者への表示を停止</button></article>)}{!state.slots.some(s=>s.published&&s.source_available!==false)&&<p className={styles.empty}>現在、保護者に表示中の日程はありません。</p>}
 <div className={styles.panel}><h2>担任別のNotion予約可</h2><p>Notion「ベンスケ」の予約可は、LINEで面談予約を開くと自動で取り込みます。翌日以降の担任の枠だけを表示し、ここで停止した日程は再開するまで表示しません。</p>{offers===null?<p>Notionの予約可を読み込んでいます…</p>:<>{offers.filter(o=>!state.slots.some(s=>s.published&&s.notion_page_id===o.pageId)).map(o=><div className={styles.actions} key={o.pageId}><span>{describe(o)}<small>{o.teacher}先生</small></span><button disabled={frozen} onClick={()=>propose({action:'publish',pageId:o.pageId},'保護者に公開する日程',`${describe(o)} ／ ${o.teacher}`)}>保護者に表示</button></div>)}{offers.filter(o=>!state.slots.some(s=>s.published&&s.notion_page_id===o.pageId)).length===0&&<p className={styles.empty}>新しく表示できる予約可はありません。</p>}</>}</div>
 </section>}
 </>}
 <footer className={styles.footer}><div className={styles.manageEntry}><small>予約の取消・面談記録はこちら</small><Link className={`${styles.button} ${styles.primary}`} href="/staff/interviews/manage">面談記録・取消・詳細管理</Link></div><div className={styles.actions}><button disabled={frozen} onClick={()=>void work(async()=>{await api('/api/staff/session',{method:'DELETE'});setStaff(null);setState(null);setOffers(null);})}>ログアウト</button></div></footer>
 </>}
 {confirm&&<FlowDialog label={confirm.title} onBack={()=>setConfirm(null)} blocked={frozen} notice={notice}><h2>{confirm.title}</h2><p>{confirm.detail}</p>{confirm.op.action==='cancel'&&<p>取り消すと保護者は新しい予約を申請できます。Notionの予定は予約可へ戻します。</p>}{confirm.reject?<label>{confirm.op.action==='cancel'?'取消理由':'保護者への連絡事項'}<textarea disabled={frozen} value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder={confirm.op.action==='cancel'?'例：日程変更のため':'別の日程をご相談させてください。'}/></label>:<p>{confirm.op.action==='approve'?'この日程で確定し、Notionへ反映します。':confirm.op.action==='publish'?'保護者の日程一覧に表示します。':'保護者の日程一覧から非表示にします。'}</p>}<button className={confirm.op.action==='cancel'?styles.danger:styles.primary} disabled={frozen||confirm.reject&&!reason.trim()} onClick={()=>void save({...confirm.op,...(confirm.reject?{reason:reason.trim()}:{})})}>{confirm.op.action==='approve'?'承認する':confirm.op.action==='cancel'?'予約を取り消す':confirm.reject?'保存する':'この内容で保存'}</button></FlowDialog>}
 </main>;
}
