'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {filterInvitationStudents} from '@/lib/interview-invitation-students.mjs';
import {blocksNewInvitation,currentInvitation,defaultInvitationTeacher,invitationProgress,invitationProgressLabels} from '@/lib/interview-invitation-flow.mjs';
import {INTERVIEW_SURVEY_CAMPAIGN} from '@/lib/interview-survey-campaign.mjs';
import {describe} from '@/app/interviews/workspace';
import FlowDialog from '@/components/flow-dialog';
import styles from '@/app/interviews/interviews.module.css';
import flow from './invitations.module.css';

type Answer={round:string;status:string;date:string|null;responses?:{id:string;date:string|null;url:string;fields:{label:string;value:string}[]}[]};
type Student={id:string|null;number:string;name:string;teacher:string;grade:string;pilot:boolean;surveys:Answer[]};
type Slot={id:string;version:number;studentId:string;date:string;start:string;end:string;teacher:string};
type Invitation={id:string;student_id:string;expires_at:string;status:string;version:number;notification_status:string;created_at:string;answerStatus?:string;campaignLabel?:string};
type State={students:Student[];rounds:{id:string;label:string}[];syncedAt:string|null;invitations:Invitation[];notifications:{booking_id:string;status:string}[];pilotReady:boolean;unmatchedSurveys?:number};
type Operation={action:string;operationKey?:string;[key:string]:unknown};
type Props={staff:{staffId:string;staffCode:string;displayName:string};onBusyChange:(busy:boolean)=>void;onRequests:()=>void;onSlots:()=>void;initialStep?:'students'|'history'};
const statusLabel:Record<string,string>={submitted:'提出済み',missing:'未提出（照合済みの記録なし）',unknown:'要確認',active:'回答受付中',revoked:'取消済み',declined:'日程が合わない',pending:'送信待ち',sending:'送信処理中',retry:'再確認が必要',sent:'LINE送信処理済み',blocked:'送信停止・要確認',obsolete:'通知対象外',not_applicable:'通知対象外'};
const japanTime=(value:string)=>new Date(value).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'});
export default function InterviewInvitations({staff,onBusyChange,onRequests,onSlots,initialStep='students'}:Props){
 const [state,setState]=useState<State|null>(null),[message,setMessage]=useState(''),[refreshError,setRefreshError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState<Operation|null>(null),[confirm,setConfirm]=useState(false);
 const [round,setRound]=useState<string>(INTERVIEW_SURVEY_CAMPAIGN.id),[teacher,setTeacher]=useState(''),[status,setStatus]=useState('submitted'),[progress,setProgress]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('date-desc');
 const [step,setStep]=useState<'students'|'slots'|'history'>(initialStep),[selected,setSelected]=useState(''),[answerStudent,setAnswerStudent]=useState<Student|null>(null);
 const [slots,setSlots]=useState<Slot[]>([]),[chosen,setChosen]=useState<string[]>([]),[expires,setExpires]=useState(''),[loadedStudent,setLoadedStudent]=useState(''),[slotsLoading,setSlotsLoading]=useState(false),[slotError,setSlotError]=useState(''),[slotReload,setSlotReload]=useState(0);
 const [slotsFetchedAt,setSlotsFetchedAt]=useState<string|null>(null);
 const [now,setNow]=useState(()=>Date.now());const lock=useRef(false),initialized=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const prefKey=`bentan:interview-survey-filters:${staff.staffId}:${INTERVIEW_SURVEY_CAMPAIGN.id}`;
 const api=useCallback(async(init?:RequestInit,suffix='')=>{const r=await fetch('/api/staff/interview-invitations'+suffix,{...init,cache:'no-store'});const b=await r.json();if(!r.ok)throw Object.assign(Error(b.error??'接続できませんでした。'),{status:r.status});return b;},[]);
 const accept=useCallback((b:State)=>{setState(b);setRefreshError('');if(!initialized.current){initialized.current=true;setRound(b.rounds.find(r=>r.id===INTERVIEW_SURVEY_CAMPAIGN.id)?.id??b.rounds[0]?.id??'');let initial=defaultInvitationTeacher(staff,b.students);try{const saved=JSON.parse(localStorage.getItem(prefKey)??'null');if(saved){if(saved.teacher===''||b.students.some(s=>s.teacher===saved.teacher))initial=saved.teacher;if(['submitted','missing','unknown',''].includes(saved.status))setStatus(saved.status);if(['',...Object.keys(invitationProgressLabels)].includes(saved.progress))setProgress(saved.progress);}}catch{/* Preferences are optional. */}setTeacher(initial);}},[prefKey,staff]);
 const load=useCallback(async()=>{accept(await api());},[accept,api]);
 useEffect(()=>{let active=true;void api().then(b=>{if(active)accept(b);}).catch(e=>{if(active)setRefreshError(e.message);});const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{active=false;clearInterval(timer);};},[api,accept]);
 useEffect(()=>{if(!state)return;try{localStorage.setItem(prefKey,JSON.stringify({teacher,status,progress}));}catch{/* Private mode may disable storage. */}},[state,prefKey,teacher,status,progress]);
 const frozen=busy||!!retry;
 useEffect(()=>{onBusyChange(frozen);return()=>onBusyChange(false);},[frozen,onBusyChange]);
 useEffect(()=>{heading.current?.focus();},[step]);
 async function work(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await task();}catch(e){setMessage((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const visible:(Student&{answer:Answer})[]=useMemo(()=>[...filterInvitationStudents((state?.students??[]).filter(s=>s.pilot),{round}),...filterInvitationStudents((state?.students??[]).filter(s=>!s.pilot),{round,teacher,status,query,sort}).filter((s:Student)=>!progress||invitationProgress(currentInvitation(state?.invitations??[],s.id),now)===progress)],[state,round,teacher,status,query,sort,progress,now]);
 const picked=state?.students.find(s=>s.number===selected),times=slots.filter(s=>chosen.includes(s.id)),existing=picked?currentInvitation(state?.invitations??[],picked.id):undefined;
 const canInvite=!!picked?.pilot&&!!picked.id&&!!state?.pilotReady&&!blocksNewInvitation(existing,now);
 const slotStudent=canInvite&&step==='slots'?picked?.id??'':'';
 useEffect(()=>{if(!slotStudent)return;let active=true;const controller=new AbortController();void(async()=>{await Promise.resolve();if(!active)return;setSlotsLoading(true);setSlotsFetchedAt(null);setSlotError('');setSlots([]);setChosen([]);setLoadedStudent('');try{const b=await api({signal:controller.signal},'?slots=1');if(!active)return;setSlots(b.slots.filter((s:Slot)=>s.studentId===slotStudent).sort((a:Slot,b:Slot)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)));setSlotsFetchedAt(b.fetchedAt??null);setLoadedStudent(slotStudent);const first=b.slots.map((s:Slot)=>s.date).sort()[0];if(first){const deadline=new Date(Math.min(Date.now()+86400000,Date.parse(first+'T00:00:00+09:00')-60000));setExpires(new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(deadline).replace(' ','T'));}}catch(e){if(active)setSlotError((e as Error).message);}finally{if(active)setSlotsLoading(false);}})();return()=>{active=false;controller.abort();};},[api,slotStudent,slotReload]);
 const slotsReady=!!slotStudent&&loadedStudent===slotStudent&&!slotsLoading&&!slotError;
 const valid=canInvite&&slotsReady&&times.length>0&&!!expires&&Number.isFinite(Date.parse(expires+'+09:00'))&&Date.parse(expires+'+09:00')>now&&Date.parse(expires+'+09:00')<Math.min(...times.map(t=>Date.parse(t.date+'T00:00:00+09:00')));
 async function save(op:Operation){await work(async()=>{setRetry(op);let b;try{b=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(op)});}catch(e){if((e as {status?:number}).status&&Number((e as {status:number}).status)<500){setRetry(null);setConfirm(false);}throw e;}setRetry(null);setConfirm(false);if(op.action==='create'){setChosen([]);setStep('history');}setMessage(b.notification?.message??(b.notification?statusLabel[b.notification.status]??'通知結果を確認してください。':'打診の状態を保存しました。'));try{await load();}catch{setRefreshError('一覧を更新できませんでした。上の送信結果は保持しています。「一覧を更新」で再確認してください。');}});}
 function choose(s:Student){setSelected(s.number);setChosen([]);setMessage('');setStep(blocksNewInvitation(currentInvitation(state?.invitations??[],s.id),now)?'history':'slots');}
 const campaignLabel=state?.rounds.find(r=>r.id===round)?.label??INTERVIEW_SURVEY_CAMPAIGN.label;
 const answer=answerStudent?.surveys.find(s=>s.round===round);
 const history=state?.invitations.filter(i=>!picked||i.student_id===picked.id)??[];
 return <section aria-label="アンケートから面談の日程を打診" className={flow.root}>
  <h2 ref={heading} tabIndex={-1}>{step==='students'?'アンケートから生徒を選ぶ':step==='slots'?'打診する候補日時を選ぶ':'打診・回答の進み具合'}</h2>
  <p className={flow.caption}>{campaignLabel}</p><p className={styles.notice}>これは本番環境での検証用です。打診LINEを送信できるのは工藤の確認用生徒だけです。</p>
  <ol className={flow.steps}><li aria-current={step==='students'?'step':undefined}>1 生徒を選ぶ</li><li aria-current={step==='slots'?'step':undefined}>2 候補日時・送信確認</li><li aria-current={step==='history'?'step':undefined}>3 回答・確定を確認</li></ol>
  {message&&<p role="status" className={styles.notice}>{message}</p>}{refreshError&&<p role="alert" className={styles.notice}>{refreshError}</p>}
  {retry&&<button disabled={busy} onClick={()=>void save(retry)}>保存・送信結果を再確認</button>}
  <div className={styles.actions}>{step!=='students'&&<button disabled={frozen} onClick={()=>setStep('students')}>アンケートの生徒一覧へ</button>}<button disabled={frozen} onClick={()=>void work(load)}>一覧を更新</button><button disabled={frozen} onClick={()=>{setSelected('');setStep('history');}}>打診履歴</button></div>
  {!state?<p>{refreshError?'アンケートを取得できませんでした。一覧を更新してください。':'生徒とアンケートを読み込んでいます。'}</p>:<>
  {step==='students'&&<>
   {(state.unmatchedSurveys??0)>0&&<p className={styles.notice}>生徒を確定できない回答が{state.unmatchedSurveys}件あります。未提出と断定せず、元のアンケートと名簿を確認してください。</p>}
   <fieldset disabled={frozen} className={flow.filters}><legend>アンケート・生徒を絞り込む</legend>
    <label>対象アンケート<select value={round} onChange={e=>setRound(e.target.value)}>{state.rounds.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label>
    <label>担任<select value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">すべての担当</option>{[...new Set(state.students.map(s=>s.teacher))].filter(Boolean).sort().map(t=><option key={t} value={t}>{t}先生{t===defaultInvitationTeacher(staff,state.students)?'（自分の担当）':''}</option>)}</select></label>
    <label>アンケート提出状況<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">すべて</option>{['submitted','missing','unknown'].map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select></label>
    <label>面談の進み具合<select value={progress} onChange={e=>setProgress(e.target.value)}><option value="">すべて</option>{Object.entries(invitationProgressLabels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
    <label>生徒名・学籍番号<input value={query} onChange={e=>setQuery(e.target.value)} type="search"/></label>
    <label>並べ替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="date-desc">提出日が新しい順</option><option value="date-asc">提出日が古い順</option><option value="name">生徒名順</option><option value="number">学籍番号順</option></select></label>
   </fieldset><p>表示 {visible.length}人 <small>アンケートの提出状況と面談の進み具合を分けて表示しています。</small></p>
   <div className={flow.students}>{visible.map(s=>{const i=currentInvitation(state.invitations,s.id),p=invitationProgress(i,now);return <article className={flow.student} key={s.number} aria-label={s.name}><h3>{s.name} {s.pilot&&<span className={styles.status}>工藤・動作確認用</span>}<span className={styles.status}>{s.grade}</span></h3><small>{s.number} ／ 担任：{s.teacher||'未設定'} ／ {s.answer.date?`提出 ${s.answer.date}`:'提出日時なし'}</small><p><span className={styles.status}>アンケート：{statusLabel[s.answer.status]}</span> <span className={styles.status}>面談：{invitationProgressLabels[p]}</span></p><div className={styles.actions}><button disabled={frozen||s.answer.status!=='submitted'} onClick={()=>setAnswerStudent(s)}>回答を見る</button>{!blocksNewInvitation(i,now)&&<button className={styles.primary} disabled={frozen||!s.pilot&&s.answer.status==='unknown'||!s.id} onClick={()=>choose(s)}>日程を打診する</button>}{i&&<button disabled={frozen} onClick={()=>{setSelected(s.number);setStep('history');}}>打診・予約の詳細</button>}</div>{s.pilot&&<small>工藤の動作確認用として、アンケート未提出でも絞り込み条件にかかわらず表示しています。</small>}{!s.pilot&&<small>現在は回答の確認まで。一般家庭への送信は準備中です。</small>}</article>;})}</div>
   {!visible.length&&<p className={styles.empty}>条件に合う生徒はいません。担任・提出状況・面談の進み具合を変更してください。</p>}
   <small>最終取得：{state.syncedAt?japanTime(state.syncedAt):'未確認'}</small>
  </>}
  {step==='slots'&&picked&&<div className={styles.panel}><h3>{picked.name}さん</h3><p>{picked.grade} ／ {picked.number}<br/>面談担当：{picked.teacher||'未設定'}先生 ／ オンライン・45分</p><button disabled={frozen} onClick={()=>setAnswerStudent(picked)}>アンケート回答を見る</button>
   {!canInvite&&<p className={styles.notice}>{blocksNewInvitation(existing,now)?'すでに有効な打診・申請・予約があります。打診履歴から状況を確認してください。':!picked.pilot?'現在は工藤の確認用生徒だけに送信できます。一般家庭への打診はまだ開始していません。':'検証用の送信設定が停止中です。設定を確認してください。'}</p>}
   {canInvite&&<><p>Notion「ベンスケ」の担任の「予約可」から、打診する候補日時を選びます。候補を送った段階では枠を確保しません。</p>{slotsLoading&&<p role="status">Notionの予約可を読み込んでいます…</p>}{slotsReady&&<div className={styles.actions}><small>Notionから取得：{slotsFetchedAt?japanTime(slotsFetchedAt):'取得済み'} ／ {slots.length}枠</small><button disabled={frozen} onClick={()=>setSlotReload(n=>n+1)}>Notionの予約可を更新</button><small>更新すると候補日時の選択は解除されます。</small></div>}{slotError&&<><p role="alert">{slotError}</p><button disabled={frozen} onClick={()=>setSlotReload(n=>n+1)}>日程をもう一度読み込む</button></>}
   {slotsReady&&!slots.length&&<><p>現在、打診できる日程はありません。</p><button disabled={frozen} onClick={onSlots}>担当の受付日程を確認</button></>}
   {[...new Set((slotsReady?slots:[]).map(s=>s.date))].sort().map(date=><div key={date} className={flow.date}><label className={styles.choice}><input type="checkbox" disabled={frozen} checked={slots.filter(s=>s.date===date).every(s=>chosen.includes(s.id))} onChange={e=>{const ids=slots.filter(s=>s.date===date).map(s=>s.id);setChosen(old=>e.target.checked?[...new Set([...old,...ids])]:old.filter(id=>!ids.includes(id)));}}/><strong>{date} の枠を選択</strong></label>{slots.filter(s=>s.date===date).map(s=><label className={styles.choice} key={s.id}><input type="checkbox" disabled={frozen} checked={chosen.includes(s.id)} onChange={()=>setChosen(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id])}/>{s.start}〜{s.end}</label>)}</div>)}
   <label>回答期限（日本時間）<input type="datetime-local" value={expires} disabled={frozen} onChange={e=>setExpires(e.target.value)}/></label><small>現在より後、最初の面談日の前日まで。既存の案内受付期限に従います。</small><p>送信先：確認済みの工藤アカウント（検証用の本人）</p><button className={styles.primary} disabled={frozen||!valid} onClick={()=>setConfirm(true)}>打診内容を確認</button></>}
  </div>}
  {step==='history'&&<><h3>{picked?`${picked.name}さんの打診履歴`:'打診履歴'}</h3>{!history.length&&<p>打診の記録はありません。</p>}{history.map(i=><article className={styles.panel} key={i.id}><h3>{state.students.find(s=>s.id===i.student_id)?.name??'対象生徒の登録を確認してください'}</h3><span className={styles.status}>面談：{invitationProgressLabels[invitationProgress(i,now)]}</span><p>{i.campaignLabel??'以前の打診（アンケートの記録なし）'}<br/>作成：{japanTime(i.created_at)}<br/>回答期限：{japanTime(i.expires_at)}<br/>LINE：{statusLabel[i.notification_status]}<br/>{statusLabel[i.status]}{i.status==='active'&&Date.parse(i.expires_at)<=now?'（回答期限終了）':''}</p><div className={styles.actions}>{i.answerStatus==='pending'&&<button disabled={frozen} className={styles.primary} onClick={onRequests}>希望日時を確認して承認へ</button>}{['confirmed','completed'].includes(i.answerStatus??'')&&<a className={styles.button} href="/staff/interviews/manage">確定予約・面談記録を確認</a>}{['pending','retry','sending'].includes(i.notification_status)&&<button disabled={frozen} onClick={()=>void save({action:'retryInvitation',id:i.id})}>打診LINEの送信を再確認</button>}{i.status==='active'&&i.answerStatus!=='confirmed'&&<button disabled={frozen} onClick={()=>{if(window.confirm('この打診を取り消しますか？回答済みの希望も再案内待ちになります。確定した予約は取り消せません。'))void save({operationKey:crypto.randomUUID(),action:'revoke',id:i.id,version:i.version});}}>打診を取り消す</button>}</div>{i.status==='active'&&i.answerStatus==='unanswered'&&Date.parse(i.expires_at)>now&&<small>有効な打診があります。重ねて新しい打診を作成せず、この履歴から対応します。</small>}</article>)}<h3>確定LINEの状態</h3>{state.notifications.length===0&&<p>確定通知はありません。</p>}{state.notifications.map(n=><article className={styles.panel} key={n.booking_id}><p>{statusLabel[n.status]}</p>{['pending','retry','sending'].includes(n.status)&&<button disabled={frozen} onClick={()=>void save({action:'retryConfirmation',id:n.booking_id})}>確定LINEの送信を再確認</button>}</article>)}<small>LINE送信処理済みは、既読や到達を意味しません。送信失敗でも確定した予約は保持します。</small></>}
  </>}
  {answerStudent&&<FlowDialog label="アンケート回答" onBack={()=>setAnswerStudent(null)}><h2>{answerStudent.name}さんの回答</h2><p>{campaignLabel}</p>{!answer?.responses?.length?<p>この画面で表示できる回答がありません。提出状況と元のアンケートを確認してください。</p>:answer.responses.map((r,index)=><article key={r.id}><h3>{index===0?'最新の回答':'以前の回答'} ／ {r.date??'日時不明'}</h3>{r.fields.map(f=><div key={f.label} className={flow.answer}><strong>{f.label}</strong><p>{f.value}</p></div>)}<a className={styles.button} href={r.url} target="_blank" rel="noreferrer">回答原本をNotionで見る</a></article>)}</FlowDialog>}
  {confirm&&picked&&<FlowDialog label="面談日程の打診確認" onBack={()=>setConfirm(false)} blocked={frozen} notice={message?<p role="status">{message}</p>:undefined}><h2>この内容で日程を打診します</h2><p>{campaignLabel}<br/>対象：{picked.name}さん<br/>担当：{picked.teacher}先生<br/>送信先：確認済みの工藤アカウント（検証用の本人）<br/>オンライン面談・45分<br/>回答期限：{expires.replace('T',' ')}（日本時間）</p><ul>{times.map(s=><li key={s.id}>{describe(s)}</li>)}</ul><p>LINEには「工藤専用・動作確認」、オンライン面談の案内日、担当、回答期限、希望日時を回答する専用リンクを記載します。アンケートの回答本文は送りません。</p><p>打診や希望回答の段階では予約は確定しません。職員が承認後に確定LINEを送ります。</p><button disabled={frozen||!valid} className={styles.primary} onClick={()=>void save({operationKey:crypto.randomUUID(),action:'create',studentId:picked.id,campaignId:round,slots:times.map(s=>({id:s.id,version:s.version})),expiresAt:new Date(expires+'+09:00').toISOString()})}>LINEで日程を打診する（工藤のみ）</button>{retry&&<button disabled={busy} onClick={()=>void save(retry)}>保存・送信結果を再確認</button>}</FlowDialog>}
 </section>;
}
