'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {filterInvitationStudents} from '@/lib/interview-invitation-students.mjs';
import {describe} from '@/app/interviews/workspace';
import FlowDialog from '@/components/flow-dialog';
import styles from '@/app/interviews/interviews.module.css';
type Student={id:string|null;number:string;name:string;teacher:string;grade:string;pilot:boolean;surveys:{round:string;status:string;date:string|null}[]};
type Slot={id:string;version:number;studentId:string;date:string;start:string;end:string;teacher:string};
type Invitation={id:string;student_id:string;expires_at:string;status:string;version:number;notification_status:string;created_at:string;answerStatus?:string};
type State={students:Student[];rounds:{id:string;label:string}[];syncedAt:string|null;invitations:Invitation[];notifications:{booking_id:string;status:string}[];pilotReady:boolean;unmatchedSurveys?:number};
type Operation={action:string;operationKey?:string;[key:string]:unknown};
const statusLabel:Record<string,string>={submitted:'提出済み',missing:'未提出（記録なし）',unknown:'要確認',active:'回答受付中',revoked:'取消済み',declined:'日程が合わない',pending:'送信待ち',sending:'送信処理中',retry:'再確認が必要',sent:'LINE送信処理済み',blocked:'送信停止・要確認',obsolete:'通知対象外'};
export default function InterviewInvitations(){
 const [state,setState]=useState<State|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState<Operation|null>(null),[confirm,setConfirm]=useState(false);
 const [round,setRound]=useState(''),[teacher,setTeacher]=useState(''),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[sort,setSort]=useState('date-desc');
 const [selected,setSelected]=useState<string[]>([]),[slots,setSlots]=useState<Slot[]>([]),[chosen,setChosen]=useState<string[]>([]),[expires,setExpires]=useState('');const lock=useRef(false);
 const api=useCallback(async(init?:RequestInit,suffix='')=>{const r=await fetch('/api/staff/interview-invitations'+suffix,{...init,cache:'no-store'});const b=await r.json();if(!r.ok)throw Object.assign(Error(b.error??'接続できませんでした。'),{status:r.status});return b;},[]);
 const load=useCallback(async()=>{const b=await api();setState(b);setRound(old=>b.rounds.some((r:{id:string})=>r.id===old)?old:b.rounds[0]?.id??'');},[api]);
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{let active=true;void(async()=>{try{const b=await api();if(active){setState(b);setRound(b.rounds[0]?.id??'');}}catch(e){if(active)setMessage((e as Error).message);}})();const timer=setInterval(()=>setNow(Date.now()),30000);return()=>{active=false;clearInterval(timer);};},[api]);
 async function work(task:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await task();}catch(e){setMessage((e as Error).message);}finally{lock.current=false;setBusy(false);}}
 const visible:(Student&{answer:{status:string;date:string|null}})[]=useMemo(()=>filterInvitationStudents(state?.students??[],{round,teacher,status,query,from,to,sort}),[state,round,teacher,status,query,from,to,sort]);
 const picked=state?.students.filter(s=>selected.includes(s.number))??[],times=slots.filter(s=>chosen.includes(s.id));
 const canInvite=picked.length===1&&picked[0].pilot&&!!picked[0].id&&state?.pilotReady;
 const frozen=busy||!!retry,valid=canInvite&&times.length>0&&!!expires&&Number.isFinite(Date.parse(expires+'+09:00'))&&Date.parse(expires+'+09:00')>now&&Date.parse(expires+'+09:00')<Math.min(...times.map(t=>Date.parse(t.date+'T00:00:00+09:00')));
 async function save(op:Operation){await work(async()=>{setRetry(op);let b;try{b=await api({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(op)});}catch(e){if((e as {status?:number}).status&&Number((e as {status:number}).status)<500){setRetry(null);setConfirm(false);}throw e;}setRetry(null);setConfirm(false);if(op.action==='create'){setChosen([]);setSelected([]);}setMessage(b.notification?.message??(b.notification?statusLabel[b.notification.status]??b.notification.status:'保存しました。'));try{await load();}catch{setMessage('保存しました。一覧の再取得に失敗しました。更新してください。');}});}
 function toggle(number:string){setSelected(old=>old.includes(number)?old.filter(n=>n!==number):[...old,number]);setChosen([]);}
 return <section aria-label="面談の日程案内"><h2>生徒を選んで日程を案内</h2><p className={styles.notice}>これは本番環境での検証用です。送信できるのは工藤の確認用生徒だけです。他の保護者には送信しません。</p>{message&&<p role="status" className={styles.notice}>{message}</p>}{retry&&<button disabled={busy} onClick={()=>void save(retry)}>保存・送信結果を再確認</button>}<button disabled={frozen} onClick={()=>void work(load)}>一覧を更新</button>
 {!state?<p>生徒とアンケートを読み込んでいます。</p>:<>{(state.unmatchedSurveys??0)>0&&<p className={styles.notice}>生徒を確定できない回答が{state.unmatchedSurveys}件あります。未提出と表示された場合も、元のアンケート一覧をご確認ください。</p>}<fieldset disabled={frozen} className={styles.panel}><legend>生徒を絞り込む</legend><label>対象アンケート<select value={round} onChange={e=>setRound(e.target.value)}>{!state.rounds.length&&<option value="">アンケートなし</option>}{state.rounds.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select></label><small>現在の面談アンケートをNotionから取得しています。対象回の開始日を確認してください。未提出は照合できた回答がない状態です。対象学年外や紐付け不明は要確認です。</small><label>担任<select value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">すべて</option>{[...new Set(state.students.map(s=>s.teacher))].filter(Boolean).sort().map(t=><option key={t}>{t}</option>)}</select></label><label>提出状況<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">すべて</option>{['submitted','missing','unknown'].map(s=><option value={s} key={s}>{statusLabel[s]}</option>)}</select></label><label>生徒名・学籍番号<input value={query} onChange={e=>setQuery(e.target.value)} type="search"/></label><label>回答提出日・開始<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>回答提出日・終了<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>並べ替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="date-desc">提出日が新しい順</option><option value="date-asc">提出日が古い順</option><option value="teacher">担任順</option><option value="missing">未提出を先に</option><option value="submitted">提出済みを先に</option><option value="name">生徒名順</option><option value="number">学籍番号順</option></select></label><small>日付不明は末尾。期間を指定すると日付のある回答だけを表示します。最終取込：{state.syncedAt?new Date(state.syncedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認'}</small>{from&&to&&from>to&&<p role="alert">開始日は終了日以前にしてください。</p>}</fieldset>
 <p>表示 {visible.length}人 ／ 選択 {selected.length}人（表示外 {selected.filter(n=>!visible.some(s=>s.number===n)).length}人）</p><div className={styles.actions}><button disabled={frozen} onClick={()=>{setSelected(old=>[...new Set([...old,...visible.map(s=>s.number)])]);setChosen([]);}}>表示中をすべて選択</button><button disabled={frozen} onClick={()=>{setSelected([]);setChosen([]);}}>選択を解除</button></div>
 <div style={{maxHeight:480,overflowY:'auto'}}>{visible.map(s=><label key={s.number} className={styles.choice}><input type="checkbox" checked={selected.includes(s.number)} disabled={frozen} onChange={()=>toggle(s.number)}/><span><strong>{s.name}</strong> ／ {s.number}<small>{s.grade} ／ 担任：{s.teacher||'未設定'}<br/>{statusLabel[s.answer.status]} ／ {s.answer.date??'提出日なし'}{!s.pilot&&' ／ 今回は送信対象外'}</small></span></label>)}{!visible.length&&<p>該当する生徒はいません。</p>}</div>
 <div className={styles.panel}><h3>選択した生徒と案内日程</h3><p>{picked.map(s=>s.name).join('、')||'生徒を選択してください。'}</p>{!!selected.length&&!canInvite&&<p>現在は工藤の確認用生徒（2018999）だけを選択すると送信できます。</p>}<button disabled={frozen||!canInvite} onClick={()=>void work(async()=>{const b=await api(undefined,'?slots=1');setSlots(b.slots);setChosen([]);setMessage(b.slots.length?'案内する日付・時間を選択してください。':'現在、案内できる担任の空き日程はありません。');})}>担任の空き日程を取得</button>
 {[...new Set(slots.map(s=>s.date))].sort().map(date=><div key={date}><label className={styles.choice}><input type="checkbox" disabled={frozen||!canInvite} checked={slots.filter(s=>s.date===date).every(s=>chosen.includes(s.id))} onChange={e=>{const ids=slots.filter(s=>s.date===date).map(s=>s.id);setChosen(old=>e.target.checked?[...new Set([...old,...ids])]:old.filter(id=>!ids.includes(id)));}}/><strong>{date} の枠を選択</strong></label>{slots.filter(s=>s.date===date).map(s=><label className={styles.choice} key={s.id}><input type="checkbox" disabled={frozen||!canInvite} checked={chosen.includes(s.id)} onChange={()=>setChosen(old=>old.includes(s.id)?old.filter(id=>id!==s.id):[...old,s.id])}/>{s.start}〜{s.end}</label>)}</div>)}
 <label>回答期限（日本時間）<input type="datetime-local" value={expires} disabled={frozen} onChange={e=>setExpires(e.target.value)}/></label><small>現在より後、最初の面談日の前日までを指定してください。</small><p>送信先：確認済みの工藤アカウント</p><button className={styles.primary} disabled={frozen||!valid} onClick={()=>setConfirm(true)}>案内内容を確認</button></div>
 <h3>案内履歴</h3>{state.invitations.map(i=><article className={styles.panel} key={i.id}><strong>工藤・検証用</strong><p>{({unanswered:'未回答',pending:'承認待ち',confirmed:'予約確定',cancelled:'予約取消済み',rejected:'再案内待ち',completed:'実施済み'} as Record<string,string>)[i.answerStatus??'unanswered']} ／ {statusLabel[i.status]}{i.status==='active'&&Date.parse(i.expires_at)<=now?'（回答期限終了）':''}<br/>回答期限：{new Date(i.expires_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}<br/>{statusLabel[i.notification_status]}</p><div className={styles.actions}>{['pending','retry','sending'].includes(i.notification_status)&&<button disabled={frozen} onClick={()=>void save({action:'retryInvitation',id:i.id})}>案内LINEの送信を再確認</button>}{i.status==='active'&&<button disabled={frozen} onClick={()=>{if(window.confirm('この案内を取り消しますか？回答済みの希望も再案内待ちになります。確定済みの予約は取り消せません。'))void save({operationKey:crypto.randomUUID(),action:'revoke',id:i.id,version:i.version});}}>案内を取り消す</button>}</div></article>)}
 <h3>工藤の確定通知</h3>{state.notifications.map(n=><article className={styles.panel} key={n.booking_id}><p>{statusLabel[n.status]}</p>{['pending','retry','sending'].includes(n.status)&&<button disabled={frozen} onClick={()=>void save({action:'retryConfirmation',id:n.booking_id})}>確定LINEの送信を再確認</button>}</article>)}<small>LINE送信処理済みは既読を意味しません。</small>
 </>}{confirm&&<FlowDialog label="面談案内の送信確認" onBack={()=>setConfirm(false)} blocked={frozen} notice={message?<p role="status">{message}</p>:undefined}><h2>この内容で工藤へ案内します</h2><p>対象：{picked.map(s=>s.name).join('、')}<br/>送信先：確認済みの工藤アカウント<br/>オンライン面談・45分<br/>回答期限：{expires.replace('T',' ')}（日本時間）</p><ul>{times.map(s=><li key={s.id}>{describe(s)} ／ {s.teacher}先生</li>)}</ul><p>LINE文面：オンライン面談の日程をご案内します。案内日・回答期限を記載し、LINE下部の「面談予約」から希望時間を選ぶよう案内します。「工藤専用・動作確認」と明記します。</p><button disabled={frozen||!valid} className={styles.primary} onClick={()=>void save({operationKey:crypto.randomUUID(),action:'create',studentId:picked[0]?.id,slots:times.map(s=>({id:s.id,version:s.version})),expiresAt:new Date(expires+'+09:00').toISOString()})}>工藤だけに案内LINEを送る</button>{retry&&<button disabled={busy} onClick={()=>void save(retry)}>送信結果を再確認</button>}</FlowDialog>}</section>;
}
