'use client';
import { FormEvent,useEffect,useRef,useState } from 'react';
import { defaults,generateSlots,normalizeTeacher,validateAppointment } from '@/lib/interview-core.mjs';
import { getJapanDate } from '@/lib/reservation-date.mjs';
import StaffEntry from '../self-study-room/staff-entry';
import styles from './workspace.module.css';
import {makeRecordDraft,validateRecord} from '@/lib/interview-record.mjs';
import {RecordFields,RecordDetails,type RecordDraft} from './record-fields';

type Staff={staffId:string;displayName:string;role:string};
type Student={id:string|null;student_number:string;student_name:string;grade:string;campus:string;homeroom_teacher:string};
type Appointment={studentId:string;teacher:string;date:string;start:string;end?:string;campus:string;method:string;purpose:string;participants:string;channel:string;note:string;room:string;studentName?:string;studentNumber?:string;grade?:string;busyStart?:string;busyEnd?:string;record?:Partial<RecordDraft>&{content:string;state:string}};
type Booking={id:string;data:Appointment;status:string;version:number;notion_page_id:string|null;notion_synced_version:number;sync_error:string|null};
type State={snapshot:string;students:Student[];teachers:string[];lessons:Record<string,unknown>[];bookings:Booking[];slots:{key:string;data:{hidden:boolean}}[];settings:{data:typeof defaults;notion_status:string};canEdit:boolean};
type Operation={operationKey:string;snapshot:string;action:string;id?:string;version?:number;data?:unknown;reason?:string;manualReviewed?:boolean;externalReviewed?:boolean};
const labels:Record<string,string>={pending:'承認待ち',confirmed:'確定',completed:'実施済み',cancelled:'取消済み',rejected:'見送り'};
const empty=():Appointment=>({studentId:'',teacher:'',date:getJapanDate(),start:'13:00',campus:'本校',method:'対面',purpose:'学習相談',participants:'保護者',channel:'職員入力',note:'',room:''});
export default function InterviewWorkspace(){
 const [staff,setStaff]=useState<Staff|null>(null),[state,setState]=useState<State|null>(null),[ready,setReady]=useState(false);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[code,setCode]=useState(''),[password,setPassword]=useState('');
 const [date,setDate]=useState(getJapanDate()),[teacher,setTeacher]=useState(''),[campus,setCampus]=useState('本校');
 const [form,setForm]=useState<Appointment|null>(null),[editing,setEditing]=useState<Booking|null>(null),[search,setSearch]=useState('');
 const [reason,setReason]=useState(''),[manualReviewed,setManualReviewed]=useState(false),[externalReviewed,setExternalReviewed]=useState(false);
 const [pending,setPending]=useState<Operation|null>(null),[retry,setRetry]=useState<Operation|null>(null);
 const [settings,setSettings]=useState<typeof defaults|null>(null),[history,setHistory]=useState<{action:string;reason:string;created_at:string}[]|null>(null);
 const [record,setRecord]=useState<{booking:Booking;value:RecordDraft}|null>(null);
 const running=useRef(false);
 async function request(url:string,init?:RequestInit){
  const r=await fetch(url,{...init,cache:'no-store',credentials:'same-origin'});const body=await r.json();
  if(!r.ok){if(r.status===401){setStaff(null);setState(null);setForm(null);setRecord(null);setHistory(null);setPending(null);setRetry(null);}throw Object.assign(new Error(body.error??'接続できませんでした。'),{status:r.status});}return body;
 }
 async function work(task:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setMessage('');try{await task();}catch(e){setMessage(e instanceof Error?e.message:'処理に失敗しました。');}finally{running.current=false;setBusy(false);}}
 async function reload(){const data=await request('/api/staff/interviews');setState(data);setTeacher(old=>old||data.teachers[0]||'');}
 useEffect(()=>{let active=true;void(async()=>{try{const r=await fetch('/api/staff/session',{cache:'no-store'});const b=await r.json();if(!active)return;if(r.ok){setStaff(b.staff);const q=await fetch('/api/staff/interviews',{cache:'no-store'});const data=await q.json();if(!active)return;if(q.ok){setState(data);setTeacher(data.teachers[0]||'');}else setMessage(data.error);}else if(r.status!==401)setMessage(b.error);}catch{if(active)setMessage('接続できませんでした。');}finally{if(active)setReady(true);}})();return()=>{active=false;};},[]);
 async function login(e:FormEvent){e.preventDefault();await work(async()=>{const secret=password;setPassword('');const b=await request('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staffCode:code,password:secret})});setStaff(b.staff);await reload();});}
 async function execute(op:Operation){await work(async()=>{
  setPending(null);setRetry(op);
  let result;
  try{result=await request('/api/staff/interviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(op)});}catch(e){if((e as {status?:number}).status&&((e as {status:number}).status<500))setRetry(null);throw e;}
  setRetry(null);setForm(null);setEditing(null);setSettings(null);setRecord(null);await reload();setMessage(result.sync?.message??'保存しました。');
 });}
 function propose(action:string,data?:unknown,row?:Booking){if(!state)return;try{if(['create','update'].includes(action))data=validateAppointment(data,state.settings.data);if(['complete','record'].includes(action)&&row)data=validateRecord(data,row.data,action);setMessage('');setPending({operationKey:crypto.randomUUID(),snapshot:state.snapshot,action,data,id:row?.id,version:row?.version,reason,manualReviewed,externalReviewed});}catch(e){setMessage(e instanceof Error?e.message:'入力内容を確認してください。');}}
 function openForm(row?:Booking,start?:string){setEditing(row??null);setForm(row?{...row.data}:{...empty(),date,teacher,campus,start:start??'13:00'});setSearch('');setReason('');setManualReviewed(false);setExternalReviewed(false);}
 function change(key:keyof Appointment,value:string){setForm(old=>old?{...old,[key]:value}:old);}
 let slots:ReturnType<typeof generateSlots>=[],slotError='';
 if(state&&teacher){try{slots=generateSlots({date,teacher,campus,lessons:state.lessons,bookings:state.bookings,settings:state.settings.data});}catch(e){slotError=e instanceof Error?e.message:'予約枠を計算できません。';}}
 const students=state?.students.filter(s=>!search||`${s.student_name}${s.student_number}${s.grade}`.normalize('NFKC').replace(/\s/g,'').includes(search.normalize('NFKC').replace(/\s/g,'')))??[];
 return <main className={`shell ${styles.main}`}><header className={styles.header}><div><p className="eyebrow">面談</p><h1>面談の予定・入力</h1><p>授業の空き時間から予約可を表示し、生徒・担当・日時をまとめて登録します。</p></div>{staff&&<div><p>{staff.displayName}</p><button disabled={busy} onClick={()=>void work(async()=>{await request('/api/staff/session',{method:'DELETE'});setStaff(null);setState(null);setForm(null);setRecord(null);setHistory(null);setPending(null);setRetry(null);})}>ログアウト</button></div>}</header>
 {message&&<p role="status" className={styles.feedback}>{message}</p>}
 {!ready?<p>読み込み中…</p>:!staff?<section className="panel"><h2>職員ログイン</h2><form onSubmit={login}><StaffEntry code={code} onChange={setCode} disabled={busy}/><label>パスワード<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||!code}>ログイン</button></form></section>:<>
 <div className={styles.toolbar}><button disabled={busy} onClick={()=>void work(reload)}>最新の予定を読み込む</button>{state?.canEdit&&<><button disabled={busy||!!retry} onClick={()=>openForm()}>面談を登録</button><button disabled={busy||!!retry} onClick={()=>setSettings({...state.settings.data})}>予約枠の設定</button></>}</div>
 {retry&&<section className={styles.notice}><p>保存結果を確認できていません。同じ操作番号で再確認できます。</p><button disabled={busy} onClick={()=>void execute(retry)}>保存結果を確認・再試行</button></section>}
 {state&&<><p className={styles.note}>自動作成枠は職員のみの表示です。保護者への予約公開・LINE送信は行いません。</p><p className={styles.notice}>Notion連携：{state.settings.notion_status}。確定前に既存予定を確認してください。</p>
 <section className="panel"><h2>予約可</h2><div className={styles.filters}><label>日付<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>担当講師<select value={teacher} onChange={e=>setTeacher(e.target.value)}>{state.teachers.map(t=><option key={t}>{t}</option>)}</select></label><label>校舎<select value={campus} onChange={e=>setCampus(e.target.value)}><option>本校</option><option>南教室</option></select></label></div>
 <p>面談{state.settings.data.duration}分。18:35～20:05の時間帯は、開始時刻を選んで1件だけ受け付けます。</p>
 {slotError?<p role="alert">{slotError}</p>:slots.length===0?<p>自動作成できる枠がありません。この校舎で担当授業がない日などは、勤務・開校状況を確認して「面談を登録」から入力できます。</p>:<div className={styles.slots}>{slots.map(slot=>{const hidden=state.slots.some(s=>s.key===slot.key&&s.data.hidden);return <div className={hidden?styles.hiddenSlot:styles.slot} key={slot.key}><strong>{slot.start}～{slot.end}</strong><span>{hidden?'非公開':'予約可'}</span>{state.canEdit&&<><button disabled={busy||hidden||!!retry} onClick={()=>openForm(undefined,slot.start)}>この時刻で入力</button><button disabled={busy||!!retry} onClick={()=>propose('slot',{key:slot.key,hidden:!hidden})}>{hidden?'予約可に戻す':'非公開にする'}</button></>}</div>;})}</div>}
 </section>
 <section className="panel"><h2>{date}の面談</h2><div className={styles.list}>{state.bookings.filter(row=>row.data.date===date).sort((a,b)=>a.data.start.localeCompare(b.data.start)).map(row=><article className={styles.booking} key={row.id}><div><span className={styles.badge}>{labels[row.status]}</span><h3>{row.data.start}～{row.data.end}　{row.data.studentName}</h3><p>{row.data.grade}・{row.data.studentNumber} ／ {row.data.teacher} ／ {row.data.campus}{row.data.room?` ${row.data.room}教室`:''} ／ {row.data.method}</p><p>目的：{row.data.purpose}　参加者：{row.data.participants}</p>{row.data.note&&<p>{row.data.note}</p>}{row.data.record&&<details><summary>面談記録（{row.data.record.state==='final'?'確定':'下書き'}）</summary><RecordDetails value={row.data.record}/></details>}<p className={styles.note}>{row.notion_page_id&&row.notion_synced_version===row.version?'Notion反映済み':'Notion未反映'}</p></div><div className={styles.actions}>
 {state.canEdit&&['pending','confirmed'].includes(row.status)&&<><button disabled={busy||!!retry} onClick={()=>openForm(row)}>変更</button>{row.status==='pending'&&<button disabled={busy||!!retry} onClick={()=>{setEditing(row);setReason('');setExternalReviewed(false);setManualReviewed(false);setPending(null);setForm(null);}}>承認・見送り</button>}<button disabled={busy||!!retry} onClick={()=>{setEditing(row);setForm(null);setReason('');setExternalReviewed(false);}}>取消・状態の変更</button>{row.status==='confirmed'&&<button disabled={busy||!!retry} onClick={()=>{setReason('');setRecord({booking:row,value:makeRecordDraft(row.data)});}}>実施済み・記録入力</button>}</>}
 {state.canEdit&&row.status==='completed'&&<button disabled={busy||!!retry} onClick={()=>{setReason('');setRecord({booking:row,value:makeRecordDraft(row.data)});}}>面談記録を編集</button>}
 {state.canEdit&&row.status!=='pending'&&<button disabled={busy||!!retry} onClick={()=>void work(async()=>{const result=await request('/api/staff/interviews/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id})});await reload();setMessage(result.message);})}>Notionへ反映</button>}
 <button disabled={busy} onClick={()=>void work(async()=>setHistory((await request(`/api/staff/interviews/history?id=${row.id}`)).events))}>変更履歴</button></div></article>)}{!state.bookings.some(r=>r.data.date===date)&&<p>この日の登録はありません。</p>}</div></section>
 <details className="panel"><summary>別の日の面談予定</summary><ul>{[...new Set(state.bookings.map(b=>b.data.date))].sort().map(d=><li key={d}><button onClick={()=>setDate(d)}>{d}（{state.bookings.filter(b=>b.data.date===d).length}件）</button></li>)}</ul></details>
 </>}
 </>}
 {form&&state&&<section className={styles.overlay} role="dialog" aria-modal="true" aria-label="面談予定の入力"><div className={styles.dialog}><h2>{editing?'面談予定の変更':'面談予定の入力'}</h2><form onSubmit={e=>{e.preventDefault();propose(editing?'update':'create',form,editing??undefined);}}><label>生徒を検索<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="氏名・学籍番号・学年"/></label><label>生徒<select required value={form.studentId} onChange={e=>{const s=state.students.find(s=>s.id===e.target.value);if(s)setForm({...form,studentId:s.id!,teacher:normalizeTeacher(s.homeroom_teacher)||form.teacher,campus:['本校','南教室'].includes(s.campus)?s.campus:form.campus});}}><option value="">選択してください</option>{state.students.filter(s=>students.includes(s)||s.id===form.studentId).map(s=><option key={s.student_number} value={s.id??''} disabled={!s.id}>{s.grade} {s.student_name}（{s.student_number}・{s.campus}）{!s.id?' 台帳の紐づけ確認が必要':''}</option>)}</select></label>
 <div className={styles.filters}><label>担当講師<select required value={form.teacher} onChange={e=>change('teacher',e.target.value)}><option value="">選択してください</option>{state.teachers.map(t=><option key={t}>{t}</option>)}</select></label><label>日付<input required type="date" value={form.date} onChange={e=>change('date',e.target.value)}/></label><label>開始時刻<input required type="time" value={form.start} onChange={e=>change('start',e.target.value)}/></label><label>校舎<select value={form.campus} onChange={e=>change('campus',e.target.value)}><option>本校</option><option>南教室</option></select></label><label>教室（未割当可）<input value={form.room} inputMode="numeric" onChange={e=>change('room',e.target.value)}/></label><label>方法<select value={form.method} onChange={e=>change('method',e.target.value)}>{['対面','Zoom','電話','ハイブリッド'].map(t=><option key={t}>{t}</option>)}</select></label></div>
 <label>面談目的<input required value={form.purpose} maxLength={500} onChange={e=>change('purpose',e.target.value)}/></label><label>参加予定者<input required value={form.participants} maxLength={500} onChange={e=>change('participants',e.target.value)} placeholder="本人、母、父など"/></label><label>受付方法<select value={form.channel} onChange={e=>change('channel',e.target.value)}>{['職員入力','LINE','電話','口頭'].map(t=><option key={t}>{t}</option>)}</select></label><label>事前相談・メモ<textarea value={form.note} maxLength={3000} onChange={e=>change('note',e.target.value)}/></label>
 <label className={styles.check}><input type="checkbox" checked={manualReviewed} onChange={e=>setManualReviewed(e.target.checked)}/>自動作成枠以外の場合、担当講師の勤務・開校状況を確認しました</label>
 {editing&&<label>変更理由<input required value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label>}
 {editing?.status==='confirmed'&&<label className={styles.check}><input required type="checkbox" checked={externalReviewed} onChange={e=>setExternalReviewed(e.target.checked)}/>変更後の日時についてNotionの既存予定・担当講師の対応可否を確認しました</label>}
 <p>保存後は{editing?.status==='confirmed'?'確定済み予定の変更':'承認待ち'}になります。授業・面談の重複を保存時に再確認します。</p><div className={styles.actions}><button disabled={busy||!!retry}>内容を確認</button><button type="button" onClick={()=>{setForm(null);setEditing(null);}}>閉じる</button></div></form></div></section>}
 {editing&&!form&&!pending&&<section className={styles.overlay} role="dialog" aria-modal="true" aria-label="面談の状態変更"><div className={styles.dialog}><h2>{editing.data.studentName}さんの面談</h2><p>{editing.data.date} {editing.data.start} ／ {editing.data.teacher} ／ {labels[editing.status]}</p><label className={styles.check}><input type="checkbox" checked={externalReviewed} onChange={e=>setExternalReviewed(e.target.checked)}/>Notionの既存予定・担当講師の対応可否を確認しました</label><label className={styles.check}><input type="checkbox" checked={manualReviewed} onChange={e=>setManualReviewed(e.target.checked)}/>自動作成枠以外の場合、勤務・開校状況を確認しました</label><label>変更・取消・見送りの理由<input value={reason} onChange={e=>setReason(e.target.value)}/></label><div className={styles.actions}>{editing.status==='pending'&&<><button disabled={busy||!externalReviewed} onClick={()=>propose('confirm',undefined,editing)}>承認して確定</button><button disabled={busy||!reason.trim()} onClick={()=>propose('reject',undefined,editing)}>見送る</button></>}<button disabled={busy||!reason.trim()} onClick={()=>propose('cancel',undefined,editing)}>予約を取り消す</button><button onClick={()=>setEditing(null)}>閉じる</button></div></div></section>}
 {record&&<section className={styles.overlay} role="dialog" aria-modal="true" aria-label="面談記録"><div className={styles.dialog}><h2>{record.booking.status==='completed'?'面談記録の入力':'面談を実施済みにする'}</h2><p>{record.booking.data.studentName} ／ {record.booking.data.date}</p><RecordFields value={record.value} onChange={value=>setRecord({...record,value})}/>{message&&<p role="alert">{message}</p>}{record.booking.data.record?.state==='final'&&<label>修正理由<input value={reason} onChange={e=>setReason(e.target.value)}/></label>}<p>記録は勉たん内に保存します。Notionの面談履歴DBへの反映は未接続です。</p><div className={styles.actions}><button disabled={busy||!!retry} onClick={()=>propose(record.booking.status==='completed'?'record':'complete',{...record.value,state:'draft'},record.booking)}>下書き保存</button>{record.booking.status==='completed'&&<button disabled={busy||!!retry} onClick={()=>propose('record',{...record.value,state:'final'},record.booking)}>記録を確定</button>}<button onClick={()=>setRecord(null)}>閉じる</button></div></div></section>}
 {settings&&<section className={styles.overlay} role="dialog" aria-modal="true" aria-label="予約枠の設定"><div className={styles.dialog}><h2>予約枠の設定</h2><div className={styles.filters}>{([['duration','面談時間（分）'],['buffer','予備時間（分）'],['step','開始時刻の刻み（分）']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" max="120" value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}{([['start','自動表示の開始'],['flexibleStart','選択時間帯の開始'],['flexibleEnd','選択時間帯の終了']] as const).map(([key,label])=><label key={key}>{label}<input type="time" value={settings[key]} onChange={e=>setSettings({...settings,[key]:e.target.value})}/></label>)}</div><label>日中の開始時刻（カンマ区切り）<input value={settings.daytime.join(',')} onChange={e=>setSettings({...settings,daytime:e.target.value.split(',').map(s=>s.trim())})}/></label><label>夜の開始時刻（カンマ区切り）<input value={settings.evening.join(',')} onChange={e=>setSettings({...settings,evening:e.target.value.split(',').map(s=>s.trim())})}/></label><p>既に登録した面談の日時は変更しません。</p><div className={styles.actions}><button disabled={busy} onClick={()=>propose('settings',settings)}>設定を保存</button><button onClick={()=>setSettings({...defaults})}>既定値に戻す</button><button onClick={()=>setSettings(null)}>閉じる</button></div></div></section>}
 {history&&<section className={styles.overlay} role="dialog" aria-modal="true" aria-label="変更履歴"><div className={styles.dialog}><h2>変更履歴</h2>{history.map((e,i)=><p key={i}>{new Date(e.created_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} ／ {({create:'登録',update:'変更',confirm:'承認',cancel:'取消',reject:'見送り',complete:'実施済み',record:'記録の保存'} as Record<string,string>)[e.action]??e.action} {e.reason}</p>)}<button onClick={()=>setHistory(null)}>閉じる</button></div></section>}
 {pending&&<section className={styles.confirmOverlay} role="dialog" aria-modal="true" aria-label="保存前の確認"><div className={styles.dialog}><h2>この内容で保存しますか</h2><p>{({create:'面談を承認待ちとして登録',update:'面談予定を変更',confirm:'面談を承認して確定',cancel:'面談を取消',reject:'申請を見送り',complete:'面談を実施済みとして記録を下書き保存',record:'面談記録を保存',settings:'予約枠の設定を変更',slot:'予約枠の表示を変更'} as Record<string,string>)[pending.action]}</p>{(form||editing)&&<p>{state?.students.find(s=>s.id===(form??editing!.data).studentId)?.student_name} ／ {(form??editing!.data).date} {(form??editing!.data).start}～{(pending.data as Appointment)?.end??(form??editing!.data).end??''} ／ {(form??editing!.data).teacher} ／ {(form??editing!.data).campus}</p>}<div className={styles.actions}><button disabled={busy} onClick={()=>void execute(pending)}>保存する</button><button disabled={busy} onClick={()=>setPending(null)}>戻る</button></div></div></section>}
 </main>;
}
