'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import FlowDialog from '@/components/flow-dialog';
import styles from '@/app/interviews/interviews.module.css';

type Staff={staffId:string;staffCode:string;displayName:string;role:string};
type Action='create'|'update'|'archive'|'keep'|'skip'|'review';
type Preview={month:string;teacher:string;hash:string;lessonDays:number;summary:Record<Action,number>;campusDecisions?:Array<{date:string;campus:string;source:'selected'|'saved'}>;items:Array<{key:string;date:string;start:string;end:string;campus:string;action:Action;reason:string;needsCampusChoice?:boolean}>};
type Overview={month:string;teachers:Array<{teacher:string;status:'not-run'|'applied'|'review';lessonDays:number;activeSlots:number;reviewCount:number;finishedAt:string|null}>};
const actionLabel:Record<Action,string>={create:'作成',update:'変更',archive:'削除',keep:'変更なし',skip:'除外',review:'要確認'};
const nextMonth=()=>{const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit'}).format(new Date()).split('-').map(Number);return new Date(Date.UTC(parts[0],parts[1],1)).toISOString().slice(0,7);};
const dateTime=(value:string|null)=>value?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';

export default function AvailabilityWorkspace({entryCode=''}:{entryCode?:string}){
 const [staff,setStaff]=useState<Staff|null>(null),[ready,setReady]=useState(false),[code,setCode]=useState(entryCode),[password,setPassword]=useState('');
 const [month,setMonth]=useState(nextMonth),[preview,setPreview]=useState<Preview|null>(null),[overview,setOverview]=useState<Overview|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [campusChoices,setCampusChoices]=useState<Record<string,string>>({}),[needsRecheck,setNeedsRecheck]=useState(false);
 const lock=useRef(false),canOverview=staff&&['admin','office'].includes(staff.role);
 const api=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(path,{...init,cache:'no-store'}),body=await response.json();if(!response.ok){if(response.status===401)setStaff(null);throw Error(body.error??'接続できませんでした。');}return body;},[]);
 const work=useCallback(async(task:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await task();}catch(error){setMessage((error as Error).message);}finally{lock.current=false;setBusy(false);}},[]);
 const loadOverview=useCallback(async(target:string)=>{if(!canOverview)return;setOverview(await api(`/api/staff/interview-auto-availability?month=${encodeURIComponent(target)}&overview=1`));},[api,canOverview]);
 useEffect(()=>{let active=true;void(async()=>{try{const response=await fetch('/api/staff/session',{cache:'no-store'}),body=await response.json();if(active&&response.ok)setStaff(body.staff);else if(active&&response.status!==401)setMessage(body.error);}catch(error){if(active)setMessage((error as Error).message);}finally{if(active)setReady(true);}})();return()=>{active=false;};},[]);
 useEffect(()=>{if(!staff||!canOverview)return;let active=true;void(async()=>{try{const response=await fetch(`/api/staff/interview-auto-availability?month=${encodeURIComponent(month)}&overview=1`,{cache:'no-store'}),body=await response.json();if(!response.ok)throw Error(body.error??'全体状況を読み込めませんでした。');if(active)setOverview(body);}catch(error){if(active)setMessage((error as Error).message);}})();return()=>{active=false;};},[staff,canOverview,month]);
 async function login(event:FormEvent){event.preventDefault();await work(async()=>{const secret=password;setPassword('');const body=await api('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staffCode:code.trim().toUpperCase(),password:secret})});setStaff(body.staff);setPreview(null);});}
 async function inspect(selected:Record<string,string>={}){await work(async()=>{setPreview(null);const synced=await api(`/api/schedule/sync?month=${encodeURIComponent(month)}`,{method:'POST'});if(!['applied','unchanged'].includes(synced.status))throw Error(synced.message??'スケジュール表の反映状況を確認してください。');const query=Object.keys(selected).length?`&campusChoices=${encodeURIComponent(JSON.stringify(selected))}`:'';const result=await api(`/api/staff/interview-auto-availability?month=${encodeURIComponent(month)}${query}`);setCampusChoices(selected);setNeedsRecheck(false);setPreview(result);setMessage(synced.message??'最新のスケジュール表で確認しました。');await loadOverview(month);});}
 async function apply(){if(!preview)return;await work(async()=>{const body=await api('/api/staff/interview-auto-availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month:preview.month,previewHash:preview.hash,operationKey:crypto.randomUUID(),campusChoices})});setConfirm(false);const refreshed=await api(`/api/staff/interview-auto-availability?month=${encodeURIComponent(preview.month)}`);setPreview(refreshed);setCampusChoices({});setMessage(`${body.saved.applied.length}件をNotionへ反映しました。`);await loadOverview(preview.month);});}
 const changes=preview?preview.summary.create+preview.summary.update+preview.summary.archive:0;
 const choiceDates=preview?.items.filter(item=>item.needsCampusChoice)??[],newChoices=preview?.campusDecisions?.filter(item=>item.source==='selected')??[];
 return <main className={styles.screen}><header className={styles.header}><div><h1>予約可能枠を作る</h1><p>毎月、スケジュール表から自分の予約可を作成します。</p></div>{staff&&<small>{staff.displayName}</small>}</header>
 {message&&<p className={styles.notice} role="status">{message}</p>}
 {!ready?<p>読み込んでいます…</p>:!staff?<form className={styles.panel} onSubmit={login}><h2>職員ログイン</h2><label>職員コード<input value={code} autoCapitalize="characters" autoComplete="username" onChange={event=>setCode(event.target.value)} required/></label><label>パスワード<input type="password" value={password} autoComplete="current-password" onChange={event=>setPassword(event.target.value)} required/></label><button className={styles.primary} disabled={busy}>ログイン</button></form>:<>
 <section className={styles.panel} aria-label="自分の予約可能枠"><h2>{staff.displayName}さんの受付枠</h2><p>所定フォルダへスケジュール表を保存した後に実行してください。本人の授業から、その日の勤務校舎と空き時間を判定します。</p><label>対象月<input type="month" value={month} onChange={event=>{setMonth(event.target.value);setPreview(null);setCampusChoices({});setNeedsRecheck(false);}}/></label><button className={styles.primary} disabled={busy||!month} onClick={()=>void inspect()}>{busy?'確認中…':'スケジュール表から枠を確認'}</button>
 {preview&&<div className={styles.availabilityPreview} aria-label="予約可の反映予定"><p><strong>{preview.month} ／ {preview.teacher}先生 ／ 授業日 {preview.lessonDays}日</strong></p><div className={styles.availabilitySummary}><span>作成 {preview.summary.create}</span><span>変更 {preview.summary.update}</span><span>削除 {preview.summary.archive}</span><span>要確認 {preview.summary.review}</span><span>除外 {preview.summary.skip}</span><span>変更なし {preview.summary.keep}</span></div>{preview.items.filter(item=>item.action!=='keep').length===0?<p className={styles.empty}>変更はありません。</p>:<ul>{preview.items.filter(item=>item.action!=='keep').map(item=><li key={`${item.key}-${item.action}`} data-action={item.action}><strong>{item.date}{item.start&&` ${item.start}${item.end?`〜${item.end}`:''}`}</strong><span>{item.campus}</span><small>{actionLabel[item.action]}：{item.reason}</small></li>)}</ul>}
 {choiceDates.length>0&&<div className={styles.selected} aria-label="勤務校舎の選択"><h3>勤務校舎を選んでください</h3><p>同じ授業が両校舎に載っているため、スケジュール表だけでは判断できない日です。</p>{choiceDates.map(item=><label key={item.date}>{item.date}の勤務校舎<select value={campusChoices[item.date]??''} onChange={event=>{setCampusChoices(current=>({...current,[item.date]:event.target.value}));setNeedsRecheck(true);}}><option value="">選択してください</option><option value="本校">本校</option><option value="南教室">南教室</option></select></label>)}<button disabled={busy||!choiceDates.some(item=>campusChoices[item.date])} onClick={()=>void inspect(Object.fromEntries(Object.entries(campusChoices).filter(([,campus])=>campus)))}>選んだ校舎で枠を再確認</button></div>}
 {(preview.campusDecisions?.length??0)>0&&<p>勤務校舎の確認：{preview.campusDecisions!.map(item=>`${item.date} ${item.campus}`).join(' ／ ')}</p>}
 <button className={styles.primary} disabled={busy||needsRecheck||changes===0&&newChoices.length===0} onClick={()=>setConfirm(true)}>この内容をNotionへ反映</button>{needsRecheck&&<p className={styles.notice}>校舎を選び直したため、枠を再確認してください。</p>}{preview.summary.review>0&&<p className={styles.notice}>要確認の日には触れず、安全に処理できる枠だけを反映します。</p>}</div>}
 </section>
 <section className={styles.panel}><h2>校舎の判定</h2><p>両校舎に同じ授業が載っていても、別の授業が片方の校舎だけなら、そちらを勤務校舎にします。同じ授業しか載っていない日は、先生が校舎を選びます。異なる授業が両校舎にある日は要確認です。</p><small>授業が始まっている時間帯でも、本人の授業と重ならなければ候補に含めます。13:00は作成しません。</small></section>
 {canOverview&&<section className={styles.panel} aria-label="先生別の月次実行状況"><h2>先生別の実行状況</h2><p>{month}のスケジュール表に名前がある先生を表示します。</p>{!overview?<p>状況を読み込んでいます…</p>:overview.teachers.length===0?<p className={styles.empty}>この月の先生をまだ読み取れません。</p>:overview.teachers.map(row=><article key={row.teacher} className={styles.selected}><strong>{row.teacher}先生：{row.status==='applied'?'反映済み':row.status==='review'?'要確認あり':'未実行'}</strong><small>授業日 {row.lessonDays}日 ／ 有効な受付枠 {row.activeSlots}件{row.reviewCount?` ／ 要確認 ${row.reviewCount}件`:''} ／ 最終反映 ${dateTime(row.finishedAt)}</small></article>)}</section>}
 <div className={styles.actions}><button disabled={busy} onClick={()=>void work(async()=>{await api('/api/staff/session',{method:'DELETE'});setStaff(null);setPreview(null);setOverview(null);})}>ログアウト</button></div>
 </>}
 {confirm&&preview&&<FlowDialog label="予約可の反映確認" onBack={()=>setConfirm(false)} blocked={busy} notice={message?<p role="status">{message}</p>:undefined}><h2>この内容をNotionへ反映しますか</h2><p>{preview.month}の{preview.teacher}先生の予約可<br/>作成 {preview.summary.create}件 ／ 変更 {preview.summary.update}件 ／ 削除 {preview.summary.archive}件</p>{(preview.campusDecisions?.length??0)>0&&<p>勤務校舎の確認：{preview.campusDecisions!.map(item=>`${item.date} ${item.campus}`).join(' ／ ')}</p>}<p>手動作成、公開・打診・予約で使用中のカードは変更しません。保護者への公開も行いません。</p><button className={styles.primary} disabled={busy} onClick={()=>void apply()}>Notionへ反映する</button></FlowDialog>}
 </main>;
}
