'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import styles from './recordings.module.css';
type Rule={mode:'private'|'scheduled'|'public'|'notion';notion_page_id?:string|null;notion_error?:string;notion_checks?:{campus:string;ready:boolean;verified:boolean}[];release_at:string|null;version:number};
type Progress={id:string;test:string;campus:string;lesson:string;noAbsences:boolean;makeupComplete:boolean};
type Row={key:string;lesson:{date:string;time:string;campus:string;label:string;room:string;grade:string;class:string;subject:string};rule?:Rule;status:'hidden'|'public';jsonHidden:boolean;notionOptions?:Progress[]};
type Staff={staffId:string;displayName:string;role:string};
const jstLocal=(date:string)=>new Date(Date.parse(date)+9*3600000).toISOString().slice(0,16);
const describe=(row:Row)=>`${row.lesson.date} ${row.lesson.time} ${row.lesson.campus==='hon'?'本校':'南教室'} ${row.lesson.label || row.lesson.grade+row.lesson.class+' '+row.lesson.subject}`;
const statusLabel=(row:Row)=>row.status==='public'?'公開':row.rule?.mode==='scheduled'?`公開待ち：${jstLocal(row.rule.release_at!).replace('T',' ')}`:row.rule?.mode==='notion'?'Notionのチェック待ち':'非公開';
export default function RecordingWorkspace({initialMonth,initialKey=""}:{initialMonth:string;initialKey?:string}){
 const [staff,setStaff]=useState<Staff|null>(null),[ready,setReady]=useState(false),[code,setCode]=useState('KUDO'),[password,setPassword]=useState('');
 const [month,setMonth]=useState(initialMonth),[rows,setRows]=useState<Row[]>([]),[campus,setCampus]=useState(''),[search,setSearch]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[editingVersion,setEditingVersion]=useState(0),[mode,setMode]=useState<Rule['mode']>('private'),[release,setRelease]=useState(''),[notionPageId,setNotionPageId]=useState(''),[notionError,setNotionError]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const requestSequence=useRef(0),initialSelection=useRef(initialKey);
 const running=useRef(false),alive=useRef(true),editor=useRef<HTMLElement>(null);
 async function api(url:string,options?:RequestInit){const r=await fetch(url,{cache:'no-store',...options});const data=await r.json();if(!r.ok){if(r.status===401 || r.status===403){if(r.status===401)setStaff(null);setRows([]);setSelected(null);}throw new Error(data.error || '処理に失敗しました。');}return data;}
 const load=useCallback(async(target:string)=>{const sequence=++requestSequence.current;const r=await fetch('/api/staff/recordings?month='+target,{cache:'no-store'});const data=await r.json();if(!r.ok){if(r.status===401 || r.status===403){if(r.status===401)setStaff(null);setRows([]);setSelected(null);}throw new Error(data.error || '録画一覧を読み込めませんでした。');}if(alive.current&&sequence===requestSequence.current){setRows(data.rows);setNotionError(data.notionError || '');const selectedRow=data.rows.find((row:Row)=>row.key===initialSelection.current);if(selectedRow){setNotionPageId(selectedRow.rule?.notion_page_id || (selectedRow.notionOptions?.length===1?selectedRow.notionOptions[0].id:""));setSelected(selectedRow.key);setEditingVersion(selectedRow.rule?.version || 0);setMode(selectedRow.rule?.mode || "private");setRelease(selectedRow.rule?.release_at?jstLocal(selectedRow.rule.release_at):"");initialSelection.current="";}}},[]);
 useEffect(()=>{alive.current=true;fetch('/api/staff/session',{cache:'no-store'}).then(async r=>{if(r.ok){const d=await r.json();if(alive.current)setStaff(d.staff);}}).catch(()=>{}).finally(()=>{if(alive.current)setReady(true);});return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!staff || staff.role!=='admin')return;Promise.resolve().then(()=>{setRows([]);setSelected(null);setError('');return load(month);}).catch(e=>{if(alive.current)setError(e.message);});},[staff,month,load]);
 async function work(fn:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'処理に失敗しました。');}finally{running.current=false;setBusy(false);}}
 async function login(e:FormEvent){e.preventDefault();await work(async()=>{const d=await api('/api/staff/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staffCode:code,password})});setPassword('');setStaff(d.staff);});}
 const current=rows.find(r=>r.key===selected);
 const visible=rows.filter(row=>(!campus||row.lesson.campus===campus)&&(!search||describe(row).normalize("NFKC").toLowerCase().includes(search.normalize("NFKC").toLowerCase())));
 function choose(row:Row){setNotionPageId(row.rule?.notion_page_id || (row.notionOptions?.length===1?row.notionOptions[0].id:""));setSelected(row.key);setEditingVersion(row.rule?.version || 0);setMode(row.rule?.mode || 'private');setRelease(row.rule?.release_at?jstLocal(row.rule.release_at):'');setNotice('');setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);}
 async function save(e:FormEvent){e.preventDefault();if(!current)return;await work(async()=>{const saved=await api('/api/staff/recordings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:current.key,version:editingVersion,mode,releaseAt:release,notionPageId})});setEditingVersion(saved.rule?.version || editingVersion+1);setNotice('公開設定を保存しました。カレンダーはこの設定に従います。公開JSONの更新には数分かかる場合があります。');await load(month);});}
 return <main className={styles.workspace}><header className={styles.header}><div><h1>録画の公開設定</h1><p>単元テスト解説など、授業ごとに公開するタイミングを設定します。</p></div>{staff&&<button disabled={busy} onClick={()=>void work(async()=>{await api('/api/staff/session',{method:'DELETE'});requestSequence.current++;setStaff(null);setRows([]);setSelected(null);setNotice('');})}>ログアウト</button>}</header>
 {error&&<p role="alert" className={styles.error}>{error}</p>}{notice&&<p role="status" className={styles.message}>{notice}</p>}
 {!ready?<p>ログイン状態を確認しています…</p>:!staff?<form className={styles.panel} onSubmit={login}><h2>管理者ログイン</h2><label>職員コード<input value={code} onChange={e=>setCode(e.target.value)} autoComplete="username" disabled={busy} required/></label><label>パスワード<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" disabled={busy} required/></label><button className={styles.primary} disabled={busy} type="submit">ログイン</button></form>:staff.role!=='admin'?<section className={styles.panel}><h2>管理者専用です</h2><p>このアカウントでは録画の公開設定を変更できません。</p></section>:<>
 <section className={styles.panel}><p>{staff.displayName}さんとして操作しています。</p><div className={styles.filters}><label>対象年月<input type="month" value={month} onChange={e=>setMonth(e.target.value)} disabled={busy}/></label><label>校舎<select value={campus} onChange={e=>setCampus(e.target.value)}><option value="">すべて</option><option value="hon">本校</option><option value="minami">南教室</option></select></label><label>授業を探す<input type="search" placeholder="例：1S、数学、2026-10-01" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><button disabled={busy} onClick={()=>void work(()=>load(month))}>最新の状態に更新</button></section>
 {current&&<section ref={editor} className={styles.panel} aria-label="選択した録画の設定"><h2>{describe(current)}</h2><form onSubmit={save} className={styles.panel}><label>公開方法<select value={mode} onChange={e=>setMode(e.target.value as Rule['mode'])} disabled={busy}><option value="private">非公開</option><option value="scheduled">日時を指定して公開</option><option value="public">今すぐ公開</option><option value="notion">Notionのチェックで公開</option></select></label>{mode==='notion'&&<><label>Notionの対象行<select value={notionPageId} onChange={e=>setNotionPageId(e.target.value)} disabled={busy} required><option value="">対象行を選択してください</option>{current.notionOptions?.map(p=><option key={p.id} value={p.id}>{p.test} ／ {p.campus} ／ {p.lesson}</option>)}</select></label>{notionError&&<p role="alert">{notionError}</p>}{!current.notionOptions?.length&&<p>この録画と一致するNotionの対象行がありません。校舎・クラス・科目・テスト回を確認してください。</p>}<p>同じ学年・クラス・科目・テスト回の本校と南教室について、各教室で「欠席なし」または「振替者採点・入力」にチェックが入ると公開します。片方だけの完了では公開しません。実施日が違っていても両教室の完了を待ちます。チェックを外すと再び非公開になります。開いているカレンダーは30秒ごとに確認します。</p>{current.rule?.notion_checks?.map(check=><p key={check.campus}>{check.campus}：{!check.verified?"進捗行を確認できません":check.ready?"完了":"チェック待ち"}</p>)}{current.rule?.notion_error&&<p role="alert">{current.rule.notion_error}</p>}</>}{mode==='scheduled'&&<label>公開日時（日本時間）<input type="datetime-local" value={release} onChange={e=>setRelease(e.target.value)} disabled={busy} required/></label>}<p>{mode==='private'?'録画リンクを隠し、自動更新でも非公開設定を維持します。':mode==='scheduled'?'指定日時まで録画リンクを隠します。PCを閉じても公開予約は有効です。':mode==='notion'?'Notionを確認できない間は非公開を維持します。':'この授業の録画リンクを公開します。'}</p><div className={styles.actions}><button className={mode==='private'?styles.danger:styles.primary} disabled={busy || (mode==='notion'&&!current.notionOptions?.some(p=>p.id===notionPageId))} type="submit">{busy?'保存中…':'この設定で保存'}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>設定を閉じる</button></div></form></section>}
 <section className={styles.cards} aria-label="録画の一覧">{visible.length===0?<p>対象の録画はありません。</p>:visible.map(row=><article key={row.key} className={styles.card}><div className={styles.detail}><strong>{describe(row)}</strong><span className={`${styles.badge} ${row.status==='hidden'?styles.hidden:''}`}>{statusLabel(row)}</span>{row.rule&&<small className={styles.muted}>{row.status==='hidden'?(row.jsonHidden?'公開JSONから録画URLを非表示済み':'公開JSONの更新待ち'):(row.jsonHidden?'公開JSONの更新待ち':'公開JSONに録画URLを掲載済み')}</small>}</div><button aria-label={`${describe(row)}の公開設定`} disabled={busy} onClick={()=>choose(row)}>公開設定</button></article>)}</section>
 <p className={styles.muted}>この設定は勉たん・カレンダーの掲載を制御します。すでに保存された録画の直接URLは無効化しません。</p>
 </>}</main>;
}
